# Generated by Django 5.2.6 on 2025-12-15 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('edificio', 'numero'), name='unique_departamento_por_edificio'),
        ),
    ]
