# Generated by Django 5.2.6 on 2025-12-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_departamento_unique_departamento_por_edificio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departamento',
            name='unique_departamento_por_edificio',
        ),
    ]
